
version: 2

models:
  - name: view_sales_profit_by_category
    description: "First check for wallmart dataset"
    columns:
      - name: Order_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: view_sales_by_region
    description: "Double check"
    tests:          
      - dbt_utils.expression_is_true:
          expression: "profit >= sales"

  - name: view_marketing
    description: "Triple check"
    tests:          
        - unique
        - not_null

  - name: view_logistica
    description: "Check again"
    tests:          
        - unique
        - not_null